### ISSUE TITLE
comparison with a revision tree. 

### ISSUE THREAD

**Issue by benoitc** [ricardobcl/Dotted-Version-Vectors#3]
was rereading the readme and still asking myself how does a dvvset compare to a revision tree history like in couchdb. what are the key differences if you already thought about that?

**Comment by benoitc** [comment]
closing. Server Wide Clocks is probably the right thing to compare, though I have hard time to figure the different usage between Dotted Version Vectors, Server Wide Clocks or Interval Tree Clocks :) Is there any paper that explains their usage?

**Comment by ricardobcl** [comment]
I am not very familiar with revision trees in CouchDB, but from the little I saw, it seems very familiar with Hash Histories (http://www.cs.fsu.edu/~awang/courses/cop5611_s2015/hash.pdf).
I will have to read the paper again to remember some stuff.
What is the best source of documentation for revision trees in couchDB, in your opinion?

Regarding DVV, SWC and ITC, they all solve the issue of detecting write conflicts (at least). 
Some observations:
- ITC were designed for cases where the rate of nodes leaving and entering the system (churn rate) is very high. ITC dynamically adapts its representation to the current number of nodes. I think performance was one issue with high number of nodes (the id space becomes increasingly fragmented), but not 100% sure.
- DVV is a strictly better alternative to traditional Version Vectors (or Vector Clocks as some people call them), where individual conflicts (in a single key) are correctly tracked and can be removed, instead of treating all conflicts (of the same key) the same, as is done in normal Version Vectors.
- SWC is the newer mechanism, and it has the most promise. It is as correct as DVVs, scales with node churn as ITCs, but it is more complicated. Other nice capabilities are deleting data safely and without coordination; act as the principal mechanism to maintain nodes synchronized and up-to-date with each other (also referred as Anti-Entropy protocols, such as Merkle Trees in Riak/Cassandra).

So, DVVs are the safe bet since they are a better version of Version Vectors and it's already used in production (e.g. Riak). SWC is still difficult to understand and/or use as it is right now in github (I think).

I'm currently working on a paper comparing SWC and DVV's, but with less math and more tests than the current one (http://haslab.uminho.pt/tome/files/global_logical_clocks.pdf) :)

**Comment by benoitc** [comment]
@ricardobcl Thanks for the explanation and link.

 I had a look at the Hash Histories paper and it looks indeed very similar to revision trees in couch. I found this link about the revision tree: http://docs.couchdb.org/en/1.6.1/replication/conflicts.html which is a general overview unfortunately.

About SWC, I am currently asking myself if it could be used for some kind of multi master replication. Do you think it could fit?

**Comment by ricardobcl** [comment]
@benoitc The appeal I see in Revision Trees is for systems where the users can update data locally, instead of issuing operations to the database, like peer-2-peer systems. Since Version Vectors and relatives (DVV/SWC) are usually proportional to the number of writers, using them in situations where users are also servers is less than ideal (see https://github.com/ricardobcl/Dotted-Version-Vectors#client-ids).

Revision Trees seems to suffer from the same problem DVV resolve in comparison with VV (see https://github.com/ricardobcl/Dotted-Version-Vectors#client-ids for an example).

I'm not sure, but it seems that CouchDB allows users to "cache" values and update them, syncing with the DB or other users periodically. I would not use DVV's in that case. ITC could be a solution, but they gradually degrade in fragmentation with failures (id space lost cannot be reclaimed).

---------------

Regarding SWC, they are supposed to be used in multi-master systems, since they were designed with Dynamo-style DBs in mind, i.e., every node is a master and therefore can make writes locally without coordination.

**Comment by benoitc** [comment]
@ricardobcl thanks for the answer :) This is very helpful as usual :)

Rev trees could be pruned and keep the last usable branches. I guess it should be feasible to reduce the growth by non incrementing the history if the same user send an update on the last version. I will think more about it.

Waiting that I am thinking to use SWC to share metadata between some nodes instead of using DVV like does the project plumtree. Will try at least :) Your DottedDB project is interesting btw :) Will keep you updated.

**Comment by ricardobcl** [comment]
@benoitc From what I understand, older data versions are alredy being pruned from Revision Trees in CoucbDB. I think it still maintains metadata, at least for some time before compaction. So I don't see a big size growth problem with it.

I didn't even know plumtree used DVV :) 
SWC has some pretty great features, but I will have to rethink the code to a general library/framework to integrate with other projects. Right now the SWC github has the code for the logical clocks (1 for the nodes and 1 for the keys), while DottedDB has the remaining logical to tie it tighter.

Anyway, thanks for the questions and thanks for the work you have done in your projects :)
