### ISSUE TITLE
error in example?

### ISSUE THREAD

**Issue by benoitc** [ricardobcl/Dotted-Version-Vectors#9]
In the put_ack section : 
https://github.com/ricardobcl/Dotted-Version-Vectors#usage-1

you write:

```erlang
   AckContext = dvvset:join(Dot),
    %% acknowledge the write with the context AckContext
    DVVSet = dvvset:sync([LocalDVVSet, Dot]),
    %% store DVVSet...
```

I believe that `LocalDVVSet` is `AckContext`,  isn't it?

**Comment by ricardobcl** [comment]
Can't believe I didn't see this notification.
There are issues with the example, yes.

The first mistake was calling the result of the dvvset:event/2/3 Dot. Actually, it is a DVVSet.
Then, on the first example, there is no Local

On the first example, since there is no LocalDVVSet, since it's the first write to that key, so the result of the event is already the final DVVSet to store.

You can see the intended use case here: https://github.com/ricardobcl/Dotted-Version-Vectors/blob/cd11282befa5711f0bbe2471078bd2a7bb332b4e/src/dvvset_prune_put_ack.erl#L516-L554

(I still plan to refresh/rewrite this codebase sooner rather than later... 👍 )
